In [21]:
import numpy as np
path = "data_set/datingTestSet.txt"

In [22]:
data = [ ]
labels =[ ]
open_file = open(path,mode='r',encoding='GBK')
STR = open_file.read()
lines = STR.split('\n')
for line in lines[:-1]:
    f_l = line.split('\t')
    x1,x2,x3,label = float(f_l[0]),float(f_l[1]),float(f_l[2]),f_l[3]
    data.append([x1,x2,x3]) 
    labels.append(label)
    
data = np.array(data)
labels = np.array(labels)
print(data)
print(labels)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]
['largeDoses' 'smallDoses' 'didntLike' 'didntLike' 'didntLike' 'didntLike'
 'largeDoses' 'largeDoses' 'didntLike' 'largeDoses' 'didntLike'
 'didntLike' 'smallDoses' 'didntLike' 'didntLike' 'didntLike' 'didntLike'
 'didntLike' 'smallDoses' 'largeDoses' 'smallDoses' 'didntLike'
 'smallDoses' 'largeDoses' 'smallDoses' 'largeDoses' 'smallDoses'
 'largeDoses' 'smallDoses' 'didntLike' 'largeDoses' 'didntLike'
 'largeDoses' 'didntLike' 'smallDoses' 'didntLike' 'didntLike'
 'smallDoses' 'largeDoses' 'largeDoses' 'didntLike' 'smallDoses'
 'largeDoses' 'largeDoses' 'largeDoses' 'didntLike' 'didntLike'
 'didntLike' 'didntLike' 'smallDoses' 'smallDoses' 'didntLike'
 'largeDoses' 'smallDoses' 'smallDoses' 'smallDoses' 'smallDos

In [23]:
max_ = np.max(data,axis=0)
min_ = np.min(data,axis=0)

In [24]:
print(max_)
print(min_)

[9.1273000e+04 2.0919349e+01 1.6955170e+00]
[0.       0.       0.001156]


In [25]:
new_data = (data - min_) / (max_ - min_)

In [26]:
new_data

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test = train_test_split(new_data,labels,test_size=0.3,random_state=42)

In [1]:
def KNN_Model(train_data,y_train,test_data,y_test,K):
    predict_labels = []
    for test in test_data[0:5,...]:
        distance = train_data -test
        square = np.power(distance,2)
        sum_ = np.sum(square,axis = 1)
        sqrt = np.sqrt(sum_)
        argsort = np.argsort(distance)[:K]
        labels = y_train[argsort]
        bin_labels = np.bincount(labels)
        predict = np.argmax(bin_labels)
        predict_labels.append(predict)
        
PREDICT = np.array(predict_labels)

acc = np.sum(np.equal(PREDICT,y_test[:10])) / PREDICT.size
print('The test accuracy is :{} %'.format(acc * 100))

NameError: name 'np' is not defined

In [2]:
x_train,shape

NameError: name 'x_train' is not defined